python  ./train.py \
            --root_dir './' \
            --root_data_dir './Datasets/Sentinel2_Lucas/' \
            --emb_path './Datasets/Lucas_Frozen_Embeddings/lucas_clipemb512_ViTB32.pt' \
            --sen_path './Datasets/Benchmark_Path_Files/train_sentinel_paths.npy'\
            --h5data_train_path './Datasets/Sen4Map/datapub.fz-juelich.de/sen4map/split_wise/1x1_crops/train.h5'\
            --h5data_val_path './Datasets/Sen4Map/datapub.fz-juelich.de/sen4map/split_wise/1x1_crops/val.h5'\
            --version_fold 'test'\
            --saved_model './checkpoints/TimeSenCLIP/'\
            --ts_arch 'TimeSenCLIP' \
            --BATCH_SIZE 64 \
            --NUM_WORKERS 8 \
            --NUM_EPOCHS 100 \
            --logit_learn